<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<OutputPath>$(ProjectDir)..\BuildOutput\plugins\T3Menu-API\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Configuration>Release</Configuration>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\T3MenuShared\T3MenuSharedAPI.csproj" />
		<Content Include="T3Menu-API.toml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>..\..\configs\plugins\T3Menu-API\T3Menu-API.toml</TargetPath>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371" />
	</ItemGroup>

</Project>
