<Project Sdk="Microsoft.NET.Sdk">


	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
		<OutputPath>$(ProjectDir)..\BuildOutput\shared\T3MenuSharedAPI\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<Configuration>Release</Configuration>
		<DebugType>none</DebugType>
	</PropertyGroup>


	<ItemGroup>
	  <PackageReference Include="CounterStrikeSharp.API" Version="1.0.371" />
	</ItemGroup>

</Project>
